spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    secret: '{cipher}AQAZ/3YIPMKD4iGVzWtugNXKxLWiBwYLQ05geqbe/5KN540ICqY680pkfDip8QteBwgHPRqSJaHiplhAWb3VYIH3oV00s5MBnKaY+NLqbA20S49lWQLAxc4+P/MktheHJdbaD7RhQeLFg6QulNXT+P1V7GBeBRr4amrLUNYZ/p2WaHriXpR05z7MfwWlJQwnAHbwaSf52B6osj3GLvOvbz0NJw9TqPhBSFZvjzHwtPFbFdZYbMO/3mg9WDhr5SEnR1+tOhL/by7HUx7ybtquakwrK/YgGOzhhwdzfbuwWYIAfJpb3pgQ9VCTNPQAhhjA2qKhG7uqVBnCgkp3CJLAyvuwDjpU142e/95CwypXNgqARVyrBdyMsUAght1cXvAWlHw='

token:
  expiration_time: 864000000
  secret: user_token

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is Empty