spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQA13EWVSt+a9STRtrp43sLUCMiHAV+MLOcn1FEjRhqLRQjvBxBXh31meCXPGryxuzWSjynwpt0IcsYH7HCmKwR8MgvBMbLyAFnHB8WngNLgjdoDP9BITv/sAe9zR6kDCuaq+JT2b+NLhfC8WSxa+7BpmaBkHf8yYvDC5lJhKJ0XHFPssifehrvh7iUMu27m40eWk8AKYuXfjOKEV3Eb7s4wFRlayDddj4YXXcNFEOOxnOkRgb4VDJSGAiLCsaVOAjYJYJe6dlbzMuxxTja3KhSHwM79KVXNcWWC5Xeh+sjvRq4pcaqE3OumG1uZKTdwcDNl8N/u1tx9qjB1otwrh2o3/TJEtl69F+8DXt4DuDWT6HY3/R46QYG6GiZDa1wvw/s='

token:
  expiration_time: 864000000
  secret: user_token